CREATE TABLE STATUS_MSTR (
  STATUS VARCHAR(8),
  STATUS_DESC TINYTEXT,
  PRIMARY KEY (STATUS));

CREATE TABLE EQUIPMENT_MSTR (
  EQ_CODE VARCHAR(24),
  EQ_NAME VARCHAR(50),
  EQ_QTY DECIMAL(10,2) NOT NULL,
  EQ_DESC TINYTEXT,
  PRIMARY KEY (EQ_CODE));
  

CREATE TABLE EQUIPMENT_DET (
  EQ_ID VARCHAR(20),
  EQ_CODE VARCHAR(24),
  EQ_STATUS VARCHAR(8),
  RENT_CNT SMALLINT,
  PRIMARY KEY (EQ_ID),
  FOREIGN KEY (EQ_STATUS) REFERENCES STATUS_MSTR (STATUS) ON DELETE CASCADE,
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE);

CREATE TABLE SALES_MSTR (
  SO_ID VARCHAR(20),
  SO_DT DATE,
  PRIMARY KEY (SO_ID));

CREATE TABLE SALES_DET (
  SO_ID VARCHAR(20),
  SOD_LINE INTEGER,
  EQ_ID VARCHAR(20),
  SOD_UNIT_PRICE DECIMAL(10,2) NOT NULL,
  SOD_QTY DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (SO_ID, SOD_LINE),
  FOREIGN KEY (EQ_ID) REFERENCES EQUIPMENT_DET (EQ_ID) ON DELETE CASCADE,
  FOREIGN KEY (SO_ID) REFERENCES SALES_MSTR (SO_ID) ON DELETE CASCADES);

CREATE TABLE CUSTOMER_MSTR (
  CUST_ID VARCHAR(20),
  CUST_NAME VARCHAR(50),
  CUST_PHONE VARCHAR(16),
  CUST_ADDR VARCHAR(100),
  CUST_EMAIL VARCHAR(30),
  OVERDUE_AMT DECIMAL(10,2),
  PRIMARY KEY (CUST_ID));

CREATE TABLE RESERVE_MSTR (
  RESERVE_ID VARCHAR(20),
  CUST_ID VARCHAR(20),
  PICK_DT DATETIME,
  RETURN_DT DATETIME,
  PRIMARY KEY (RESERVE_ID),
  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER_MSTR(CUST_ID) ON DELETE CASCADE);

CREATE TABLE RESERVE_DET (
  RESERVE_ID VARCHAR(20),
  EQ_CODE VARCHAR(24),
  RESERVE_QTY DECIMAL(10,2),
  PRIMARY KEY (RESERVE_ID, EQ_CODE),
  FOREIGN KEY (RESERVE_ID) REFERENCES RESERVE_MSTR (RESERVE_ID) ON DELETE CASCADE,
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE);

CREATE TABLE VENDOR_MSTR (
  VEND_ID VARCHAR(20),
  NAME VARCHAR(50),
  ADDR TINYTEXT,
  PRIMARY KEY (VEND_ID));
  
CREATE TABLE EQUIPMENT_REPAIR (
  EQ_CODE VARCHAR(24),
  VEND_ID VARCHAR(20),
  REPAIR_HRS SMALLINT,
  PRIMARY KEY (EQ_CODE, VEND_ID),
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE,
  FOREIGN KEY (VEND_ID) REFERENCES VENDOR_MSTR (VEND_ID) ON DELETE CASCADE);

CREATE TABLE PRICE_LIST_MSTR (
  EQ_CODE VARCHAR(24),
  EQ_STATUS VARCHAR(8),
  PRICE DECIMAL(10,2),
  PRIMARY KEY (EQ_CODE, EQ_STATUS),
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE,
  FOREIGN KEY (EQ_STATUS) REFERENCES STATUS_MSTR (STATUS) ON DELETE CASCADE);

CREATE TABLE RENT_MSTR (
  RENT_ID VARCHAR(20),
  RESERVE_ID VARCHAR(20),
  PICK_DT_ACTUAL DATETIME,
  RETURN_DT_ACTUAL DATETIME,
  IS_DAMAGED_RETURN BOOLEAN,
  IS_ONTIME_RETURN BOOLEAN,
  IS_NO_RETURN BOOLEAN,
  PRIMARY KEY (RENT_ID),
  FOREIGN KEY (RESERVE_ID) REFERENCES RESERVE_MSTR (RESERVE_ID) ON DELETE CASCADE);

CREATE TABLE RENT_DET (
  RENT_ID VARCHAR(20),
  EQ_ID VARCHAR(20),
  PRIMARY KEY (RENT_ID, EQ_ID),
  FOREIGN KEY (RENT_ID) REFERENCES RENT_MSTR (RENT_ID) ON DELETE CASCADE,
  FOREIGN KEY (EQ_ID) REFERENCES EQUIPMENT_DET(EQ_ID) ON DELETE CASCADE);
  
CREATE TABLE INVENTORY (
  EQ_CODE VARCHAR(24),
  INV_STATUS VARCHAR(8),
  INV_QTY DECIMAL(10,2),
  PRIMARY KEY (EQ_CODE, INV_STATUS),
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE,
  FOREIGN KEY (INV_STATUS) REFERENCES STATUS_MSTR (STATUS) ON DELETE CASCADE);

CREATE TABLE PURCHASE_MSTR (
  PO_ID VARCHAR(20),
  VEND_ID VARCHAR(20),
  PO_DT DATETIME,
  DELIVERY_DT DATETIME,
  PRIMARY KEY (PO_ID),
  FOREIGN KEY (VEND_ID) REFERENCES VENDOR_MSTR (VEND_ID) ON DELETE CASCADE);

CREATE TABLE PURCHASE_DET (
  PO_ID VARCHAR(20),
  POD_LINE INTEGER,
  EQ_CODE VARCHAR(24) NOT NULL,
  POD_UNIT_PRICE DECIMAL(10,2),
  POD_QTY DECIMAL(10,2),
  PRIMARY KEY (PO_ID, POD_LINE),
  FOREIGN KEY (PO_ID) REFERENCES PURCHASE_MSTR (PO_ID),
  FOREIGN KEY (EQ_CODE) REFERENCES EQUIPMENT_MSTR (EQ_CODE) ON DELETE CASCADE);